# Regression Model

# Importing Libraries

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("ObesityDataSet_raw.csv")
df.head()
df.shape

(2111, 17)

In [3]:
X =df[['Age','Height']]    #Using these attributes i will predict weight
y = df['Weight']  #Target I want to predict
X.shape, y.shape

((2111, 2), (2111,))

In [4]:
X

       Age    Height
0     21.0  1.620000
1     21.0  1.520000
2     23.0  1.800000
3     27.0  1.800000
4     22.0  1.780000
...    ...       ...
2106   NaN  1.710730
2107   NaN  1.748584
2108   NaN  1.752206
2109   NaN  1.739450
2110   NaN  1.738836

[2111 rows x 2 columns]

In [5]:
y

0        64.000000
1        56.000000
2        77.000000
3        87.000000
4        89.800000
           ...
2106    131.408528
2107    133.742943
2108    133.689352
2109    133.346641
2110    133.472641
Name: Weight, Length: 2111, dtype: float64

In [6]:
df.isnull().sum()

Gender                               0
Age                               1375
Height                              45
Weight                               9
family_history_with_overweight       0
FAVC                                 0
FCVC                                 0
NCP                                  0
CAEC                                 0
SMOKE                                0
CH2O                                 0
SCC                                  0
FAF                                  0
TUE                                  0
CALC                                 0
MTRANS                               0
NObeyesdad                           0
dtype: int64

## Handle missing values

In [7]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [8]:
df['Height'] = df['Height'].fillna(df['Height'].mean())

In [9]:
df['Weight'] = df['Weight'].fillna(df['Weight'].mean())

In [10]:
df.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,confusion_matrix,ConfusionMatrixDisplay

In [12]:
# X -> features -> age,height     and     y -> target ->weight
X = df[['Age','Height']]
y = df['Weight']

# Split the Dataset

In [13]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
# 20% data is for testing (80,20,80,20)

In [14]:
X.shape,y.shape

((2111, 2), (2111,))

In [15]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1688, 2), (423, 2), (1688,), (423,))

In [16]:
model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [18]:
#prediction 
y_predict = model.predict(X_test)
y_predict      #gives weight

array([ 93.79054975,  79.6095536 , 100.92959212,  60.69350423,
        91.913747  ,  86.31934913, 102.13376539,  87.0091956 ,
        69.61482323,  87.7076489 ,  82.93558737, 100.71997253,
        84.53381653,  94.2885934 ,  81.58231063,  79.81443159,
        82.32583177,  86.41506679,  96.583086  ,  87.17959136,
       107.32174193,  89.31747719,  76.78709808,  93.40603503,
        75.13335696,  66.12090396,  85.71013944, 103.20953441,
        77.01761064,  93.83675728,  83.92444414,  82.96118529,
        80.95535848,  77.47389427,  73.58840816,  85.30674246,
        92.75571657,  80.9539934 ,  54.98460617,  80.9539934 ,
        74.39042398,  94.90714418, 110.18000299, 105.8955572 ,
       106.83564398,  88.48967982,  86.86257096,  76.96552706,
        68.11174501, 102.94541638,  83.75257324,  71.93814828,
        97.44949299,  73.82064307, 103.39488961,  95.05863098,
        94.34149577, 104.78072166, 116.06205312,  75.95483748,
        95.39384613,  75.64857073, 104.21389181, 107.00367135,
        96.11221553,  79.81443159,  85.91995848, 100.05206371,
        86.43646403,  57.04025303,  83.560833  ,  98.14210127,
        86.64853677,  86.64853677,  85.09101632,  95.98973932,
       112.64243384,  75.13335696,  80.6918862 , 110.79872719,
        69.02783006,  90.14186151,  87.3271404 ,  85.16391919,
        61.2206743 ,  95.47817472,  69.59761097,  86.44223997,
        79.41780275,  79.35638906,  94.71232684,  85.8823675 ,
        86.64853677,  82.43985936,  80.21106042,  86.64853677,
        86.37800101,  77.75878473,  94.36602269,  94.06096881,
        98.60400902,  71.51681438,  79.39334962,  94.82901688,
        69.13909572,  63.66297848,  64.17360336,  93.14587596,
        76.99319416, 106.00207066,  90.73402675,  83.00964026,
        97.77332368,  73.36260055,  86.64853677,  87.71964185,
        79.88549666, 104.82535393,  90.56271758,  85.35017758,
        81.83986509, 100.38680575,  96.39458028,  81.17523806,
       108.35892189,  83.96121073,  74.50547008,  81.23391637,
       100.33114668,  93.00580939,  72.33437259, 103.5037136 ,
        94.9358036 ,  80.26867785,  86.85979343,  81.82790879,
        86.64853677,  92.86810571,  54.98460617,  79.00727025,
        83.49821654,  84.98657155,  89.39939054,  86.64853677,
        99.50513985,  96.88448511, 106.96192705,  83.51121241,
        97.80509135,  92.31845158,  72.31468188,  88.10413575,
        72.79281964,  95.9187215 ,  85.47300496,  75.56299239,
        87.97021811,  88.71165974,  87.85419503,  69.11192255,
        71.02206323,  81.23888385,  67.54283564,  69.9003385 ,
        94.10258184,  88.68850872, 101.41400436,  92.94157043,
        49.25408498,  61.15154676,  82.26670728,  94.25428431,
        95.00874824,  91.8262047 ,  60.44958617,  65.87700172,
        79.87867055,  92.70900478, 104.44177894,  73.82064307,
        80.29992044, 102.13573446,  92.77345904,  61.27318286,
       104.37286146,  97.44041944,  65.74441762,  89.62793403,
        96.05905062,  86.88147404,  70.63204522,  83.09678864,
        83.4299346 ,  89.11516716,  93.43454175,  88.09843272,
        99.08787536,  80.22048042,  92.5501664 , 108.61804689,
        96.36373151,  81.04829862,  79.53604162,  75.72366857,
        81.12714547,  98.19824916,  75.30320631, 102.04358194,
       109.21359325,  90.39521529,  70.79858647,  91.87595655,
        73.34975678,  99.9805208 ,  85.32774588,  82.1633178 ,
        87.43425785,  97.96813042,  95.62244198,  96.42166956,
        80.782726  ,  73.48015663, 109.35159141,  96.36976999,
       113.82650177, 105.99708235,  72.50738828,  72.89673922,
        71.81821349,  90.88592357,  87.40582444,  81.79535349,
        89.00342878, 100.10746023,  79.35638906,  63.37693813,
        77.82322315,  77.02483057,  97.6378516 ,  71.46233676,
        83.44636435,  94.72559585,  73.81944581, 102.68773065,
       118.0059616 ,  91.62885654,  91.913747  , 100.4920854 ,
        77.3007422 , 106.73574645,  79.89836126,  94.04086347,
        82.76756   ,  97.73438344,  97.44949299,  89.80108099,
        92.56539388, 106.04197716,  77.88754613,  74.51325136,
        74.81973379, 100.93814558, 100.53159809,  89.24934734,
        90.30230119,  74.81842107,  91.1962333 ,  67.08392158,
        77.3007422 ,  76.40181656,  98.1806588 ,  98.62855677,
       108.69413704,  86.70294495, 109.09456203,  79.87867055,
       105.201709  ,  79.31432425,  82.60570237,  86.77462984,
        86.64853677,  81.98203201,  86.41834858,  81.92281801,
        76.48399245,  83.48589286,  66.5418913 ,  87.58981445,
        99.6778197 ,  95.71827009,  97.215289  ,  98.39410607,
        88.8302767 , 110.40360031,  63.56045553,  93.05293582,
       105.64593138,  95.99092077,  87.59742819, 102.68904336,
        67.54196411,  88.079588  ,  93.45068813,  86.98924785,
        66.51235524, 108.35892189, 102.14413583, 101.20659557,
        92.48794377,  83.23422978,  73.82064307,  97.03991043,
        82.72474981,  91.94579293,  87.80943148,  83.91710354,
        67.16201734,  79.32351325,  86.47514184, 115.71574898,
        71.97993984,  61.54817559,  94.55126745,  86.64853677,
        86.77462984,  92.54845988,  68.44348864,  72.22303874,
        82.31204828,  66.79903113,  64.63164588,  86.48973939,
        93.0255001 ,  77.67658241, 101.49854314,  91.35561259,
        75.03725048,  93.72872093,  64.08987304,  81.41203592,
        85.63098279,  76.43436126,  93.58878563,  73.83532964,
        94.75736353,  93.00580939,  64.10431289,  95.26221246,
        73.77468226,  82.17185044,  84.20851031,  94.18186976,
        87.80245327,  64.45849381,  77.30299464,  66.36638146,
        92.20964842,  78.78660816, 101.96193114,  83.92506384,
        87.67986662, 105.07070016,  84.04246772, 109.01960606,
        98.89031192,  99.11491727,  75.42660141,  86.52454713,
        78.31457196,  74.21941912,  86.64853677, 102.13056762,
        57.32514349,  74.81605819,  89.58238285,  85.53384196,
        87.71460628,  70.16739187,  69.56297104,  79.81443159,
        99.28166308, 114.24836586,  96.59482163,  69.8778911 ,
        80.6689137 ,  73.33925507,  87.94661008,  92.53533274,
       113.37521167,  91.23222771,  97.09346916,  70.81621898,
        70.67562732,  80.98043131,  92.94157043,  73.82064307,
        91.01468497,  82.37150361, 100.35981121,  97.9434514 ,
        83.57942117,  67.61936686,  78.32856563,  92.00342107,
        75.57191884,  58.06807646,  86.64853677, 101.92136828,
        82.89790188,  85.21012672, 105.96006382,  78.95596396,
        64.8635866 ,  86.44223997,  80.87239496,  91.17081402,
        70.16739187,  95.83481826,  95.39384613,  79.90348084,
       101.95741555,  94.13710622,  86.3985266 ])

In [21]:
#mean absolute error 
mae = mean_absolute_error(y_test,y_predict)     #|y_test-y_predict|
mae

19.185968408359184

In [22]:
updated_df = pd.DataFrame(df[['Age','Height','Weight']])
updated_df

          Age    Height      Weight
0     21.0000  1.620000   64.000000
1     21.0000  1.520000   56.000000
2     23.0000  1.800000   77.000000
3     27.0000  1.800000   87.000000
4     22.0000  1.780000   89.800000
...       ...       ...         ...
2106  23.0625  1.710730  131.408528
2107  23.0625  1.748584  133.742943
2108  23.0625  1.752206  133.689352
2109  23.0625  1.739450  133.346641
2110  23.0625  1.738836  133.472641

[2111 rows x 3 columns]

In [23]:
updated_df1 = pd.DataFrame(X_test,y_test,y_predict)
updated_df1

,93.790550,79.609554,100.929592,60.693504,91.913747,86.319349,102.133765,87.009196,69.614823,87.707649,...,86.442240,80.872395,91.170814,70.167392,95.834818,95.393846,79.903481,101.957416,94.137106,86.398527
Weight,,,,,,,,,,,,,,,,,,,,,
53.699561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111.004920,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101.141277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
65.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113.501549,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79.677930,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
"""updated_df2 = pd.DataFrame({
    "X_test_Age":X_test.Age,
    "X_test_Height":X_test.Height,
    "y_test":y_test,
    "y_predict":y_predict
})
updated_df2"""

'updated_df2 = pd.DataFrame({\n    "X_test_Age":X_test.Age,\n    "X_test_Height":X_test.Height,\n    "y_test":y_test,\n    "y_predict":y_predict\n})\nupdated_df2'

In [25]:
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [26]:
df['Gender'] = df['Gender'].map({'Male':0,'Female':1}) #convert Categorical data into numbers

In [27]:
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,1,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,0,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,0,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,0,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [28]:
df['family_history_with_overweight'].unique()

array(['yes', 'no'], dtype=object)

In [29]:
df['family_history_with_overweight'] = df['family_history_with_overweight'].map({'yes':1,'no':0})
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21.0,1.62,64.0,1,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,1,21.0,1.52,56.0,1,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,0,23.0,1.80,77.0,1,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,0,27.0,1.80,87.0,0,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,0,22.0,1.78,89.8,0,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [30]:
df['FAVC'] = df['FAVC'].map({'yes':1,'no':0})
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21.0,1.62,64.0,1,0,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,1,21.0,1.52,56.0,1,0,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,0,23.0,1.80,77.0,1,0,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,0,27.0,1.80,87.0,0,0,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,0,22.0,1.78,89.8,0,0,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [31]:
df['CAEC'] = df['CAEC'].map({'Sometimes':1,'Frequently':0,'Always':2,'no':3})
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21.0,1.62,64.0,1,0,2.0,3.0,1,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,1,21.0,1.52,56.0,1,0,3.0,3.0,1,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,0,23.0,1.80,77.0,1,0,2.0,3.0,1,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,0,27.0,1.80,87.0,0,0,3.0,3.0,1,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,0,22.0,1.78,89.8,0,0,2.0,1.0,1,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [32]:
df['SCC'] = df['SCC'].map({'yes':1,'no':0})
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21.0,1.62,64.0,1,0,2.0,3.0,1,no,2.0,0,0.0,1.0,no,Public_Transportation,Normal_Weight
1,1,21.0,1.52,56.0,1,0,3.0,3.0,1,yes,3.0,1,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,0,23.0,1.80,77.0,1,0,2.0,3.0,1,no,2.0,0,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,0,27.0,1.80,87.0,0,0,3.0,3.0,1,no,2.0,0,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,0,22.0,1.78,89.8,0,0,2.0,1.0,1,no,2.0,0,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [33]:
df['MTRANS'].unique()

array(['Public_Transportation', 'Walking', 'Automobile', 'Motorbike',
       'Bike'], dtype=object)

In [34]:
df['MTRANS']=df['MTRANS'].map({'Public_Transportation':0,'Walking':1,'Automobile':2,'Motorbike':3,'Bike':4})
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21.0,1.62,64.0,1,0,2.0,3.0,1,no,2.0,0,0.0,1.0,no,0,Normal_Weight
1,1,21.0,1.52,56.0,1,0,3.0,3.0,1,yes,3.0,1,3.0,0.0,Sometimes,0,Normal_Weight
2,0,23.0,1.80,77.0,1,0,2.0,3.0,1,no,2.0,0,2.0,1.0,Frequently,0,Normal_Weight
3,0,27.0,1.80,87.0,0,0,3.0,3.0,1,no,2.0,0,2.0,0.0,Frequently,1,Overweight_Level_I
4,0,22.0,1.78,89.8,0,0,2.0,1.0,1,no,2.0,0,0.0,0.0,Sometimes,0,Overweight_Level_II

In [35]:
df['SMOKE']= df['SMOKE'].map({'no':0,'yes':1})

In [36]:
df['CALC'].unique()

array(['no', 'Sometimes', 'Frequently', 'Always'], dtype=object)

In [37]:
df['CALC'] = df['CALC'].map({'Sometimes':1,'Frequently':0,'Always':2,'no':3})
df.head()
df['NObeyesdad'].unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_II',
       'Obesity_Type_III'], dtype=object)

In [38]:
df['NObeyesdad']=df['NObeyesdad'].map({'Normal_Weight':0, 'Overweight_Level_I':1, 'Overweight_Level_II':2,
       'Obesity_Type_I':3, 'Insufficient_Weight':4, 'Obesity_Type_II':5,
       'Obesity_Type_III':6})
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,1,21.0,1.62,64.0,1,0,2.0,3.0,1,0,2.0,0,0.0,1.0,3,0,0
1,1,21.0,1.52,56.0,1,0,3.0,3.0,1,1,3.0,1,3.0,0.0,1,0,0
2,0,23.0,1.80,77.0,1,0,2.0,3.0,1,0,2.0,0,2.0,1.0,0,0,0
3,0,27.0,1.80,87.0,0,0,3.0,3.0,1,0,2.0,0,2.0,0.0,0,1,1
4,0,22.0,1.78,89.8,0,0,2.0,1.0,1,0,2.0,0,0.0,0.0,1,0,2

In [39]:
df.columns

Index(['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad'],
      dtype='object')

In [40]:
X  = df[['Gender', 'Age', 'Height','family_history_with_overweight',
       'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE',
       'CALC', 'MTRANS', 'NObeyesdad']]
y = df['Weight']

In [41]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)
# 20% data is for testing (80,20,80,20)

In [42]:
model=LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [43]:
#prediction 
y_predict = model.predict(X_test)
y_predict      #gives weight

array([ 81.7735381 , 108.50009026, 105.52041088,  60.22142303,
        68.09213476,  96.67050043, 115.98761273,  77.34861633,
        77.77592989,  82.72200267,  88.03047472, 121.76493162,
        98.39843383, 107.14251318, 110.06647926,  80.75414527,
       109.00248343,  98.77153871,  98.95884914,  77.79036968,
       105.88878693,  77.12015133, 106.39638052,  93.41022119,
        42.10756744,  68.93098557,  75.58640551, 122.41437285,
       107.15878748,  91.67587459, 112.03729611,  76.15420682,
        87.39744152,  62.58259922,  61.35104103, 112.40382893,
        92.48023353,  57.78290143,  46.18721674,  41.43260576,
        59.67584391, 108.31663054,  85.0154257 ,  64.34243776,
        91.45157354,  84.34652863, 100.75282997,  67.30217339,
        71.95763084, 116.24339777,  50.52126583,  55.06222085,
        83.03836991,  73.45662287, 101.25971122,  90.15005741,
       108.29070246, 116.68299561,  68.77688422,  95.16748741,
        48.69262041, 105.43613402,  97.63272164, 102.64516601,
       109.1549519 ,  95.83349006,  68.36761742, 122.70028175,
        72.81251783,  32.64845502,  76.50907408,  85.6201548 ,
        67.60228953,  86.03207026,  77.95749479, 109.1126942 ,
       123.65726093,  74.29250982, 109.46777588, 123.06183869,
        63.58988091,  84.45198098,  94.82548066, 101.67227024,
        71.75986194,  89.16726698,  58.87099293,  87.4272456 ,
        54.44227772,  86.18583864,  54.60128184,  99.47980429,
        81.59450429,  59.53735344,  84.96101218,  88.26358706,
        61.43890363,  84.48036298,  73.79545732, 107.87994078,
       100.37639664,  80.8675672 , 108.29393363,  95.09500392,
        65.12069581,  73.56814927,  38.91364784, 116.5589768 ,
       106.33641167, 121.84312172,  85.27687672,  59.15726295,
        96.88845542,  62.61207474,  77.00561061,  85.76780335,
        86.06793938, 118.17071321,  86.67717735,  69.17276403,
       110.19017096, 115.65488723,  88.29055913,  82.42373725,
        63.44046871,  97.76612578,  76.18644089,  82.98051519,
       122.36948481, 108.19582468, 102.01814996, 118.57158255,
        70.40355413,  78.16065281,  87.62584283, 110.12731872,
        94.57593174, 115.77973711,  34.11554289,  87.59204413,
        75.00034609,  88.73357045,  73.06491426,  93.95718994,
        97.23427235, 113.25920519, 105.59190146, 110.99600262,
        84.20867965,  92.76569177,  58.77370587,  86.85347514,
        27.31546927, 109.88610755,  81.69523016,  68.43662385,
        88.48617718,  78.94165867,  78.83765746,  69.17180942,
        42.29200028,  63.87395434,  76.64131224,  56.93185646,
       107.93880738,  80.16542216, 102.34950807,  62.26868461,
        30.78668234,  63.78307431,  79.01971824,  69.61152566,
       108.58803069, 115.34596531,  71.21302125,  63.2483597 ,
        85.74383675,  80.89713525, 104.16097095,  53.32763989,
        71.89324919, 116.37464023,  81.20239483,  41.24141333,
       116.63663888, 100.74035124,  46.33657674, 112.93010156,
       108.25167701, 100.71097508,  69.81017006, 111.99763541,
        94.36276504,  61.74440593, 117.27595828,  44.28785014,
       113.28086036,  89.06108794, 116.92492881, 112.94816594,
       110.43591257,  98.34095499, 108.20066992, 105.88777298,
        64.72171005, 120.09625825,  85.44277911,  64.54762098,
       124.74721953, 115.40498941,  49.97273523,  86.35499902,
        61.20545174, 101.88177071, 101.52086836,  74.22022255,
        79.51941749, 102.66482495, 108.62449438,  97.74271167,
       109.55947244,  78.21254545, 122.69471443,  76.5778696 ,
       122.99157789,  98.56529039,  55.64024879, 102.77452432,
        48.06513977,  71.76278148,  77.51414099, 110.10483957,
        53.75794991,  87.44338917,  67.05922269,  72.29975485,
        86.36225234,  86.83121891, 102.66030441,  57.67115174,
        74.89948322,  95.19849867,  71.74482351, 103.44348046,
        88.26824349,  98.16639113,  50.26322369, 102.55058142,
        74.46151908, 110.86037837,  72.54297545,  93.0934251 ,
        82.61748853,  87.55170017,  73.90741096,  89.37419681,
        86.90868163, 121.77511233,  75.29376177,  67.46405412,
       103.44863272, 121.62738893,  90.43482102,  85.72417137,
        90.88756818, 103.60713452, 114.32222031,  33.46410766,
        53.36794925, 106.49425835,  97.42467184, 120.51531719,
        91.53311066,  83.32106406, 123.36936018,  84.57622819,
       121.51942111, 108.08083668,  94.11289942,  62.98998322,
        78.64782689,  71.97544044,  82.49271133, 110.34705515,
       104.69255787,  77.63111109,  75.82809877,  80.31579614,
        98.83220529, 109.71871585, 101.32993266,  57.51533275,
        52.30340155, 108.77763803,  61.42601427,  86.56823862,
       121.7663047 , 111.16673174,  87.7203367 ,  93.30736177,
        54.1792694 ,  79.67690621,  98.92549495,  85.31070561,
        66.50149878,  64.5970772 ,  98.28964392,  89.64304981,
        86.51486204, 109.63328153,  73.45662287, 108.88447129,
        66.69608811, 115.67112022,  79.84804719,  73.22585979,
        75.54501867, 108.03668888,  84.84200404,  79.51447943,
        70.1765134 ,  30.42679762, 117.85269563,  81.51950903,
        65.96458746, 116.27032407,  77.27994479,  80.74106819,
       111.82830399,  72.03507986,  40.68876348,  48.60328185,
       107.65550771, 105.55133084, 106.45983147,  83.09019562,
        87.76853685,  90.53769902,  65.66549031, 107.84389377,
        85.70421866, 104.65868807,  92.74703899,  74.55824317,
       117.9194574 , 107.50065448,  43.44847384,  94.76382716,
        66.29791058,  74.10587124,  81.7125117 , 116.69798735,
        87.09613629,  24.96157691,  78.30580854,  60.31401286,
        82.90616775,  66.05223277,  89.41520436,  75.68574685,
        79.66700157, 118.89280906,  87.4042897 , 107.64412017,
       115.29419126, 121.12235128,  82.55725161,  81.9867604 ,
        75.44348963, 104.30609862,  77.55213837,  85.09347996,
        29.97419753,  94.13517142,  86.66931069,  76.92351121,
        80.73742452,  39.68677703,  75.63152275,  81.26617965,
        90.5920363 , 107.8258618 ,  57.68907379,  64.41849498,
       109.28044475,  68.93475982, 115.23950845, 116.49196566,
        55.27817992,  90.15908501, 108.89529099,  48.06645782,
       100.99130239,  70.72650618, 106.80823818,  73.45662287,
        66.56609554, 110.87463974,  85.33685755, 119.22662536,
        55.09665275,  63.37494841,  47.86520892,  87.88093291,
        78.96808289,  43.8403283 ,  78.06380459, 122.22511449,
        49.81303113, 109.06926162,  99.26049589,  75.27249367,
        43.30688076,  76.02504507, 109.09666139,  91.19258204,
        49.95664252,  96.12323632,  82.39226067,  94.87439764,
        77.44964554, 107.60994068,  81.21939371])

In [44]:
#mean absolute error 
mae = mean_absolute_error(y_test,y_predict)     #|y_test-y_predict|
mae

10.990350186038384

In [45]:
updated_df2 = pd.DataFrame({
    "X_test_Age":X_test.Age,
    "X_test_Height":X_test.Height,
    "y_test":y_test,
    "y_predict":y_predict
})
updated_df2

      X_test_Age  X_test_Height      y_test   y_predict
544      23.0625       1.755978   53.699561   81.773538
1987     26.0000       1.624950  111.004920  108.500090
420      18.0000       1.850000   60.000000  105.520411
527      21.0000       1.520000   42.000000   60.221423
196      22.0000       1.750000   74.000000   68.092135
...          ...            ...         ...         ...
447      19.0000       1.800000   87.000000   82.392261
1793     23.0625       1.650189  101.141277   94.874398
73       19.0000       1.850000   65.000000   77.449646
1711     23.0625       1.758618  113.501549  107.609941
1103     23.0625       1.699667   79.677930   81.219394

[423 rows x 4 columns]